os:
  - osx
  - linux
  - windows

language: node_js

node_js:
  - node
  - 10
rust:
  - stable

cache: cargo

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

before_install:
  # Install NPM packages
  - node -v
  - npm -v
  - npm install

script:
  - npm test
  # Publish when using 'publish binary' keywords
  - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "publish binary" ]]; then yarn upload-binary || exit 0; fi;