[package]
name = "emerald-vault-node"
version = "0.8.1"
authors = ["Igor Artamonov <igor@artamonov.ru>"]
license = "Apache-2.0"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "emerald_vault_node"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.9.1"

[dependencies]
emerald-vault = "0.29.1"
emerald-hwkey = "0.1"
#emerald-vault = { path = "../../../../emerald-rs" }
#emerald-hwkey = { path = "../../../../emerald-hwkey" }
#emerald-vault = { git = "https://github.com/emeraldpay/emerald-vault", branch = "master" }
#emerald-hwkey = { git = "https://github.com/emeraldpay/emerald-hwkey", branch = "master" }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
hex = "0.4.3"
hdpath = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
bitcoin = "0.27.1"
env_logger = "0.8.1"
log = "0.4.11"
byteorder = "1.4.3"

[dependencies.neon]
version = "0.9.1"
default-features = false
features = ["napi-6", "channel-api"]