[package]
name = "emerald-vault-node"
version = "0.6.0-rc.2"
authors = ["Igor Artamonov <igor@artamonov.ru>"]
license = "Apache-2.0"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "emerald_vault_node"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.9.1"

[dependencies]
neon = "0.9.1"
emerald-vault = "0.28.0"
emerald-hwkey = "0.1.0"
#emerald-vault = { path = "../../../../emerald-rs" }
#emerald-hwkey = { path = "../../../../emerald-hwkey" }
#emerald-vault = { git = "https://github.com/emeraldpay/emerald-vault", branch = "master" }
#emerald-hwkey = { git = "https://github.com/emeraldpay/emerald-hwkey", branch = "master" }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
hex = "0.4.2"
hdpath = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
bitcoin = "0.25.0"
env_logger = "0.8.1"
log = "0.4.11"
