name: Publish package

on:
  release:
    types: [created]

jobs:
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          always-auth: true

      - name: Configure NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install system libs
        run: sudo apt-get install libusb-1.0-0-dev libudev-dev

      - name: Install JS dependencies
        run: yarn install

      - name: Publish to NPM - core
        run: npm publish --access=public
        working-directory: packages/core

      - name: Publish to NPM - native
        run: npm publish --access=public
        working-directory: packages/native
        env:
          NO_NPM_BINARY: "true"
